/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //tests.testCase01();
        //END Tests


        // searchAmazon search = new searchAmazon();
        // search.searchingAmazon();
        // search.endTest();


        // BookMyShow links = new BookMyShow();
        // links.hyperlinksCount();
        // links.endTest();


        // linkedIn post = new linkedIn();
        // post.linkedIn_view();
        // post.endTest();


        BookMyShow_Movies url = new BookMyShow_Movies();
        url.MoviesUrl();
        url.endTest();


        // linkedIn_post imgPost = new linkedIn_post();
        // imgPost.createPost();
        // imgPost.endTest();

        
        //iFrames text = new iFrames();
        //text.iFramesText();
        //text.endTest();


        // ImdbRatings movie = new ImdbRatings();
        // movie.movieRating();
        // movie.endTest();

        // WindowsHandle handle = new WindowsHandle();
        // handle.handlingWindow();
        // handle.endTest();

        
        
        
    //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
